# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5556f1f4e28bbaace72cadf98d01972d9bd03ebf240ac89f613a8d5273e4aa8528e8e595eed5971bfdd6eead05e03ee6b36c20ba2d79295487929cd080cd61bc

test:
  secret_key_base: b94934c2862113e40da03599eb6f1d04ebd17590404036e73d95ba817fa06d84403636dc633c472dd2b72c6cf0d29a1962d656dc259ca6dcbb6947bdf3a36186

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
